//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubSubscribe
    {
        public int ClubSubscribe_Id { get; set; }
        public int ClubSubscribe_Club_Id { get; set; }
        public int ClubSubscribe_User_Id { get; set; }
    }
}
