//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clubs
    {
        public Clubs()
        {
            this.Event = new HashSet<Event>();
        }
    
        public int Club_Id { get; set; }
        public string Club_Name { get; set; }
        public string Club_Description { get; set; }
        public int Club_Moderator { get; set; }
    
        public virtual ICollection<Event> Event { get; set; }
    }
}
