//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRSN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCRSNContainer : DbContext
    {
        public NCRSNContainer()
            : base("name=NCRSNContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clubs> Clubs { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Comments> Comments { get; set; }
        public DbSet<EventLikeDislike> EventLikeDislikes { get; set; }
        public DbSet<ClubSubscribe> ClubSubscribes { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
